version: '3'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
    - MONGO_URI=MONGODB_URI
      - mongo_data:/data/db

  fastapi-app:
    build: .
    container_name: fastapi-app
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true

volumes:
  mongo_data: